package camp.visual.sdk.eyedid_flutter.constants

object ArgumentKey {
    const val LICENSE = "license"
    const val USE_BLINK  = "useBlink"
    const val USE_USER_STATUS = "useUserStatus"
    const val USE_GAZE_FILTER = "useGazeFilter"
    const val MAX_CONCURRENCY = "maxConcurrency"
    const val CAMERA_PRESET = "cameraPreset"
    const val MODEL_NAME = "modelName"
    const val SCREEN_WIDTH = "screenWidth"
    const val SCREEN_HEIGHT = "screenHeight"
    const val SCREEN_ORIGIN_X = "screenOriginX"
    const val SCREEN_ORIGIN_Y = "screenOriginY"
    const val CAMERA_ON_LONGER_AXIS = "cameraOnLongerAxis"
    const val CAMERA_POSITION_INDEX = "cameraPositionListIndex"
    const val TRACKING_FPS = "trackingFPS"
    const val CALIBRATION_MODE = "calibrationMode"
    const val CALIBRATION_CRITERIA = "calibrationCriteria"
    const val CALIBRATION_REGION_LEFT = "calibrationRegionLeft"
    const val CALIBRATION_REGION_TOP = "calibrationRegionTop"
    const val CALIBRATION_REGION_RIGHT = "calibrationRegionRight"
    const val CALIBRATION_REGION_BOTTOM = "calibrationRegionBottom"
    const val CALIBRATION_DATA = "calibrationData"
    const val ATTENTION_REGION_LEFT = "attentionRegionLeft"
    const val ATTENTION_REGION_TOP = "attentionRegionTop"
    const val ATTENTION_REGION_RIGHT = "attentionRegionRight"
    const val ATTENTION_REGION_BOTTOM = "attentionRegionBottom"
}