import Foundation

struct ArgumentKey {
    static let license = "license"
    static let useBlink = "useBlink"
    static let useUserStatus = "useUserStatus"
    static let useGazeFilter = "useGazeFilter"
    static let maxConcurrency = "maxConcurrency"
    static let cameraPreset = "cameraPreset"
    static let modelName = "modelName"
    static let screenWidth = "screenWidth"
    static let screenHeight = "screenHeight"
    static let screenOriginX = "screenOriginX"
    static let screenOriginY = "screenOriginY"
    static let cameraOnLongerAxis = "cameraOnLongerAxis"
    static let cameraPositionIndex = "cameraPositionListIndex"
    static let trackingFPS = "trackingFPS"
    static let calibrationMode = "calibrationMode"
    static let calibrationCriteria = "calibrationCriteria"
    static let calibrationRegionLeft = "calibrationRegionLeft"
    static let calibrationRegionTop = "calibrationRegionTop"
    static let calibrationRegionRight = "calibrationRegionRight"
    static let calibrationRegionBottom = "calibrationRegionBottom"
    static let usePreviousCalibration = "usePreviousCalibration"
    static let calibrationData = "calibrationData"
    static let attentionRegionLeft = "attentionRegionLeft"
    static let attentionRegionTop = "attentionRegionTop"
    static let attentionRegionRight = "attentionRegionRight"
    static let attentionRegionBottom = "attentionRegionBottom"
    static let orientation = "orientation"
}
